apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-tls
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC4TCCAcmgAwIBAgIUJXcFqkqNjG//v35IGZARHlJG9j4wDQYJKoZIhvcNAQEL
    BQAwIDEeMBwGA1UEAwwVU21hcnRQYXJraW5nIExvY2FsIENBMB4XDTI1MDgyMjIy
    Mjk0NVoXDTM1MDgyMTIyMjk0NVowIDEeMBwGA1UEAwwVU21hcnRQYXJraW5nIExv
    Y2FsIENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwlYKYN92dMHh
    Pig7LjHGXSZhXC8TFGu3IYd9axXEDTlDaNnY7gNBqCQMtRlqiOuNTEOhzPWbq4KY
    c6NcgDiG9lpI2VC0pDG9PoCtBqVWaD6yYxJTLx6zchEMK//IRkMWdibD5qytXwfd
    zN4RBroJDBk0CTyQod15e7mIl+leJU+7LLPJQoNr/aPEafPArXVF4tbFPtVV6Uu3
    tCa0cStF27k0iGP+edulXmCZXNYh7ChHReC5fahf+HQ8cEKLIhVro8Kfyc1CMpIp
    SVg8IuBIJEdtj74M53r/xgn3P+Cd+2oCIQR2NYN1GZQht+3WHDtiqEVjt+cZ8v7x
    AX+L+guc7wIDAQABoxMwETAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUA
    A4IBAQAM+cjfle2eAtqRlWbLk0U6DMblxFEa2mhnNzafWJumC0KM5irzh1feNS8/
    v5HnOddDoLqk0Yky8SxRKMEdrwGc1HZzyV5wOceaDRHJukTT8ZZYMYM8A/4FTJDY
    agtp78wMj0lY88+4NqtTxOm6St1ZvRsEByb9uFERduVfKO0NB13U39/hgGBmi1CU
    sH6N5xFZAFrGRwpITmx9WN/nuhGElDTJakGqfIigye9dvF6mIU0nqjhze0JyxZPL
    aGNf3jz7JQWRTMpJRKGtE6SOzf4hUTM55HYwfTWkLk5BbkjXEI8t76HdO1BFbSJL
    QATjBSe31JKgp2NZvBvumEbGjr1l
    -----END CERTIFICATE-----
  server.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDUjCCAjqgAwIBAgIUdUJXH0SAndgDRZgm91BrMb/FqaIwDQYJKoZIhvcNAQEL
    BQAwIDEeMBwGA1UEAwwVU21hcnRQYXJraW5nIExvY2FsIENBMB4XDTI1MDgyMjIy
    Mjk0NloXDTI4MDgyMjIyMjk0NlowFDESMBAGA1UEAwwJbW9zcXVpdHRvMIIBIjAN
    BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAquyQLgTlWG0QXnEDOlItO4T4Hhep
    Ve0LJlxlWnI0cjDcieGPprbM8MWmZlK/bvwuvY7s09cXxUAZCjLZZGTNXp6J7GN1
    j5ecIe7PEalhgdrYHn2X1i/CYgosELTxoFAmelHqaCb7b+R7czEi0IJ7IH/SiETI
    5dtMCMrXj3xbfUtmZTi+xGG4Aznln0PEm8Z3m0a5b86bmg6ShLVVSGdmFhPOTIqo
    hLVNQo0dpAABpNOA7OWQ2l1jLkSyHN6sOEE6d0U4H6SflkFszYZ0sdTIEZRExjK4
    ulrh0EAJ7TIdt6gCpjlFQQUlgpv75Tr1k59ZQbyK+lYRrUk3j1OfrRRljwIDAQAB
    o4GPMIGMMHUGA1UdEQRuMGyCCW1vc3F1aXR0b4IXbW9zcXVpdHRvLnNtYXJ0LXBh
    cmtpbmeCG21vc3F1aXR0by5zbWFydC1wYXJraW5nLnN2Y4IpbW9zcXVpdHRvLnNt
    YXJ0LXBhcmtpbmcuc3ZjLmNsdXN0ZXIubG9jYWwwEwYDVR0lBAwwCgYIKwYBBQUH
    AwEwDQYJKoZIhvcNAQELBQADggEBAJusXDVcz9J3vxJYGWOit/BTWnAhPIEJHbt8
    58ollVemNmrtEljqDSOrL+hTaqcSy9fJMrmLBtNy1fo6YEV/z8IedvHQxxUOfuIe
    mP70E+oWtedIff80JGRogC/qXZVFniVmF5UaSKrEoS5mKXTZdvdllmIZnNnukTSD
    +hHaF0UludUmltrRy+D6lBcCyo+DS0b6gJa/ARJIbKpZgj4GvxLP7G1mijkJi5j1
    T0xu8SdIwsgk5CBN84r58F7lan5vPizMu0I6lCakpTYlW8wXp5yE3WbiS7I9jYhQ
    uCdT93UWu/MUsIllKUwJC02A/Fvkuk2Jq1PU1PI+ZYGYgi1IPsE=
    -----END CERTIFICATE-----
  server.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAquyQLgTlWG0QXnEDOlItO4T4HhepVe0LJlxlWnI0cjDcieGP
    prbM8MWmZlK/bvwuvY7s09cXxUAZCjLZZGTNXp6J7GN1j5ecIe7PEalhgdrYHn2X
    1i/CYgosELTxoFAmelHqaCb7b+R7czEi0IJ7IH/SiETI5dtMCMrXj3xbfUtmZTi+
    xGG4Aznln0PEm8Z3m0a5b86bmg6ShLVVSGdmFhPOTIqohLVNQo0dpAABpNOA7OWQ
    2l1jLkSyHN6sOEE6d0U4H6SflkFszYZ0sdTIEZRExjK4ulrh0EAJ7TIdt6gCpjlF
    QQUlgpv75Tr1k59ZQbyK+lYRrUk3j1OfrRRljwIDAQABAoIBAQClpTchchs19BSO
    AiYnqiYt7XJr73BrVpucpKSQ3+cV12aTtWZ7IeNBX7sgpQbjL0C48j9wGZ7uyWy6
    5oap9crV7P0re0QeUca9V+uTaTyXFRini/3PVF+klckYs9MLE0IG/0YVg9nfGWXO
    QAtGWX2sBFRrPYYYxMtOJg57/v/HTuotVGcCvCqKwb4LQV3R96/m+4agRrwWzPiW
    Z3t7rtgf1XO2cV68efDs6mkhTpd8VI4hxiJJJzk9tXU5fypgB4ZzmdTaxZW80zra
    4M3lubz+SPg3vdvunAYfmq0VeHqSjprt1j6vugxe1oFs9jDKZ3qhqo8pd/u3LpGa
    j0HMQ055AoGBAN0imE859DmhgYgi+TflFEwPAVxbUcHtxxu60Ry9ZTsPyUln4yUe
    A81Hcw5orCvWfd1hwr5FKK31MasodxRvbBZTrAsfoK+p1Zle0ved6v6je7rlklf4
    Z5M0HVQaCmW1S2VvR7C55FcVKsNde9UDt7cr65lImcJQojsaa1s1EMMtAoGBAMXf
    XGzBRr/v1iHqjn6PhRRbVj3Y32QB6RekpM6JIw0R5rB1BDrm7zpgM6ZpSEOS1Wa0
    Bq8qBz6PbbrIhGN3Mh5mHIBS3TJFT0k4ZKty0iTguWigJcQqBsvjgOJUtfLq1otC
    nqzcckk109u7+TntxBYl1lul/mBA+PeCsVgWiDErAoGAB+AZiIjJ19uWn2CPe5we
    8u593+ooqT1sn+IxXFKqbkYLpx+aCVJeVEs9H8A+kXkcFmxK4TfZUQiwciYIx6OI
    N+tW7zZ7JIZp4wJrhQIMwnDUET3nzlY8ahOrD7m1sRWZz8z8wqB8L1XDph2IMXfm
    bRGVXGonf7IbdPtl42OqaykCgYAViUsI9zxZFaSLyni546sLXSmUz674tpCFJ0Fc
    zWZIPOOL3yCXvJzbEK9udFUOLcQWSo/TrtJdB8VcqAhovwdwcZK2kM5Mc2i+wmmK
    k5O1udPURGH36M8Wj+tuNuQazV6Oh7C3hcLWnwoxB1OH744BDxs2nGmEVm4CmnHs
    8X7fQwKBgEwhN2Cej1hobaYLvnwL6wL04ANeTzYxp0KuvVid4MlVOkkp94RJfmAP
    ztoeUlKreD5KA362e0HmnLpn/t4YaDbSNN2HZeqvVMxJF4qXMHpRc/jfoT15p2ZN
    mvpK0P3+SUNfgH2mVQ/Gx8iA3ypByH5rfXDWDoRU9f8LIASMtk0U
    -----END RSA PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: mqtt-client-aggregator
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC4TCCAcmgAwIBAgIUJXcFqkqNjG//v35IGZARHlJG9j4wDQYJKoZIhvcNAQEL
    BQAwIDEeMBwGA1UEAwwVU21hcnRQYXJraW5nIExvY2FsIENBMB4XDTI1MDgyMjIy
    Mjk0NVoXDTM1MDgyMTIyMjk0NVowIDEeMBwGA1UEAwwVU21hcnRQYXJraW5nIExv
    Y2FsIENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwlYKYN92dMHh
    Pig7LjHGXSZhXC8TFGu3IYd9axXEDTlDaNnY7gNBqCQMtRlqiOuNTEOhzPWbq4KY
    c6NcgDiG9lpI2VC0pDG9PoCtBqVWaD6yYxJTLx6zchEMK//IRkMWdibD5qytXwfd
    zN4RBroJDBk0CTyQod15e7mIl+leJU+7LLPJQoNr/aPEafPArXVF4tbFPtVV6Uu3
    tCa0cStF27k0iGP+edulXmCZXNYh7ChHReC5fahf+HQ8cEKLIhVro8Kfyc1CMpIp
    SVg8IuBIJEdtj74M53r/xgn3P+Cd+2oCIQR2NYN1GZQht+3WHDtiqEVjt+cZ8v7x
    AX+L+guc7wIDAQABoxMwETAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUA
    A4IBAQAM+cjfle2eAtqRlWbLk0U6DMblxFEa2mhnNzafWJumC0KM5irzh1feNS8/
    v5HnOddDoLqk0Yky8SxRKMEdrwGc1HZzyV5wOceaDRHJukTT8ZZYMYM8A/4FTJDY
    agtp78wMj0lY88+4NqtTxOm6St1ZvRsEByb9uFERduVfKO0NB13U39/hgGBmi1CU
    sH6N5xFZAFrGRwpITmx9WN/nuhGElDTJakGqfIigye9dvF6mIU0nqjhze0JyxZPL
    aGNf3jz7JQWRTMpJRKGtE6SOzf4hUTM55HYwfTWkLk5BbkjXEI8t76HdO1BFbSJL
    QATjBSe31JKgp2NZvBvumEbGjr1l
    -----END CERTIFICATE-----
  client.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC2jCCAcKgAwIBAgIUKxHl/SV/5P8G9oaNAjvw3Qo9HtIwDQYJKoZIhvcNAQEL
    BQAwIDEeMBwGA1UEAwwVU21hcnRQYXJraW5nIExvY2FsIENBMB4XDTI1MDgyMjIy
    Mjk0NloXDTI4MDgyMjIyMjk0NlowFTETMBEGA1UEAwwKYWdncmVnYXRvcjCCASIw
    DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANstgW3wpF5ILOjnIkvSurUilir8
    QI746E9jBWfThrNNwbspELVxzjCnVUQHe2L3Uh7/XRy8Zp1QDOvgHWQB+n0G/4Hk
    3DPzbWBIcHTu18mHJmqVm94IjbV02byN6XnK5yJpAj21vLWyVWG1k+BIa9HsNFt9
    ZQ8Pto0sbuScD0ULHJQlnykOE54NmGqNh10OAqDltz01M2CGyZiNLIMv123XSzOv
    c979V7E+hIQBQf9FvyAdAoNN9vZPtyvhyaUdehfICa9kKP9XA1kbdD/QP3DBYQiN
    I/IQaeYLxxU+wIFZWEfJVCc1v60M1zSLfbxwwIDYkeg7V0Oo9E0/iZ7k08UCAwEA
    AaMXMBUwEwYDVR0lBAwwCgYIKwYBBQUHAwIwDQYJKoZIhvcNAQELBQADggEBAHEg
    7PvKcY3kgvILQvWeZZNKnwRU5rsed8JKasCv33k1ysuHZ4I9en7jbI5s2qzHrUqH
    V8MrSN+ryQKSPclQzM9Hdz3T3ijtyd96nezHDOPeA8WyE08g4lWU2rGb4I/I7W5h
    L/xIX6ALps62x4bLdb1VrEK74cOskcr0nttlTaCwkRRdluZa6NY+jHnIe4oDUjNr
    r/NQudOa5po2ylJNqGdL9woKuTB3Us8RjLDGzokEyGRC/gKFdxXPmR1FG0xyZsYM
    rDOYItQhG3qmemvstkPhDioymIdrWl3A65hqHTZYT5r7+XzkoXEaBj/Ja7CJbDNp
    1pIUqbFeapgdMKpoMNQ=
    -----END CERTIFICATE-----
  client.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEA2y2BbfCkXkgs6OciS9K6tSKWKvxAjvjoT2MFZ9OGs03BuykQ
    tXHOMKdVRAd7YvdSHv9dHLxmnVAM6+AdZAH6fQb/geTcM/NtYEhwdO7XyYcmapWb
    3giNtXTZvI3pecrnImkCPbW8tbJVYbWT4Ehr0ew0W31lDw+2jSxu5JwPRQsclCWf
    KQ4Tng2Yao2HXQ4CoOW3PTUzYIbJmI0sgy/XbddLM69z3v1XsT6EhAFB/0W/IB0C
    g0329k+3K+HJpR16F8gJr2Qo/1cDWRt0P9A/cMFhCI0j8hBp5gvHFT7AgVlYR8lU
    JzW/rQzXNIt9vHDAgNiR6DtXQ6j0TT+JnuTTxQIDAQABAoIBAEjE+AcHcZs3/Wkq
    bFGeWo0POap16/1MGN1atA2/xiY798lrHfgQG/Q9amrWzRmToblW8ZQ73Rn33QJn
    e3qbyY2/SA/Za174QGVKR8QbFJv9ejzDBWgXkO0hKbWXrF/ahRkAolTYxRnSZtS1
    E67QfLPK56tEm8v/XI3MpdjTE6LJK1ym25HN9se8jy8snCGXdD8c5plp/crYgO2u
    6wHFrFjUMLBjCtUhG/qAhZ8rJeQK7FxyfDr0wWX7NVkqLbIYH4mNoot1hQQdYN4s
    xGl/CdOFaChGnnaOZC/LxFATRr8+fzil7s/WTsjtLgT0l/PniFm/DBmuhHwIxKTy
    Z4H4taECgYEA7uTBVPMLcpZdWAHZIOImTi6CviduueyY92HEReqjdhBqRhiaelS0
    Xm2QD1tMQkzf12ldq2tPW0PJEST87mAGsaRsve0hphq2zvjXkQlpBKh3IY5NAXsk
    IfM//af6tGqWO1GkB4iio+mC832U+N0n7Z960ioNkavq6IpfgeciW/0CgYEA6t9V
    IjaOlN5IV4TihztvvI7kXtzND384W0zqwMY2iikxkGZG21k5g0x/4Kll43tHsvE+
    /DO2seDBma5IoKDxQZbiuXr8NVdDACG/u7+vxTSoL3sElP9FqiaWUwLvtEpfmOIV
    ikup3exFNGMs6S1FRIR/mXNAHKYp4NJJeglKTWkCgYA3zc3vlxqseL1zSnM7ADjs
    eGboHnP6EG+nEfp0TpxCfxEkMKkdPF4p1LQbMjt9HVIIkr9jxJxz+ECmtZoz4NCP
    fJY+Q39husnLTUulwKn8gZHaj9AjMW2+VIE1MqEYtfFECA0mCV/cpDaHxGUhQSAL
    nP5my5YB2kP0cCZhROm8zQKBgQDaWAYvySIhmMcNvXZNm16Tnw8EdSWY238LuWSf
    E2VOaV8vSzVh4v+JZQuYUkJrCIct/gG8uWKE2FmCQbg4w4WkoN1i6scd22Jo8/bn
    VhrULNCRWz52OR2NQVQMFbW7GEzotnyp1Q80RNpNCkmM983mFXr9r1uRhpN18mfm
    ME7HyQKBgQC74+G+rKTd9M4Jpo0QoymSMCfeOq51zFMzcC8XT0phexeKmaXJef0U
    Rk2fz8doCtmfNnK93Tp1HpCmvv+YIU2pET9o6MgerMsm2frpfvFyex+yjhF24yS7
    JN23tEwUEmyriZSrPT9WRK/QBwS4jNmHxhI5eSYJ9wcmjK/LJeVGhQ==
    -----END RSA PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: mqtt-client-sensor
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC4TCCAcmgAwIBAgIUJXcFqkqNjG//v35IGZARHlJG9j4wDQYJKoZIhvcNAQEL
    BQAwIDEeMBwGA1UEAwwVU21hcnRQYXJraW5nIExvY2FsIENBMB4XDTI1MDgyMjIy
    Mjk0NVoXDTM1MDgyMTIyMjk0NVowIDEeMBwGA1UEAwwVU21hcnRQYXJraW5nIExv
    Y2FsIENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwlYKYN92dMHh
    Pig7LjHGXSZhXC8TFGu3IYd9axXEDTlDaNnY7gNBqCQMtRlqiOuNTEOhzPWbq4KY
    c6NcgDiG9lpI2VC0pDG9PoCtBqVWaD6yYxJTLx6zchEMK//IRkMWdibD5qytXwfd
    zN4RBroJDBk0CTyQod15e7mIl+leJU+7LLPJQoNr/aPEafPArXVF4tbFPtVV6Uu3
    tCa0cStF27k0iGP+edulXmCZXNYh7ChHReC5fahf+HQ8cEKLIhVro8Kfyc1CMpIp
    SVg8IuBIJEdtj74M53r/xgn3P+Cd+2oCIQR2NYN1GZQht+3WHDtiqEVjt+cZ8v7x
    AX+L+guc7wIDAQABoxMwETAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUA
    A4IBAQAM+cjfle2eAtqRlWbLk0U6DMblxFEa2mhnNzafWJumC0KM5irzh1feNS8/
    v5HnOddDoLqk0Yky8SxRKMEdrwGc1HZzyV5wOceaDRHJukTT8ZZYMYM8A/4FTJDY
    agtp78wMj0lY88+4NqtTxOm6St1ZvRsEByb9uFERduVfKO0NB13U39/hgGBmi1CU
    sH6N5xFZAFrGRwpITmx9WN/nuhGElDTJakGqfIigye9dvF6mIU0nqjhze0JyxZPL
    aGNf3jz7JQWRTMpJRKGtE6SOzf4hUTM55HYwfTWkLk5BbkjXEI8t76HdO1BFbSJL
    QATjBSe31JKgp2NZvBvumEbGjr1l
    -----END CERTIFICATE-----
  client.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC4DCCAcigAwIBAgIURAIezxLoAb9ZycgXsQxkZaQ8nVMwDQYJKoZIhvcNAQEL
    BQAwIDEeMBwGA1UEAwwVU21hcnRQYXJraW5nIExvY2FsIENBMB4XDTI1MDgyMjIy
    Mjk0NloXDTI4MDgyMjIyMjk0NlowGzEZMBcGA1UEAwwQc2Vuc29yLXNpbXVsYXRv
    cjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL6sxfQdV610GSEB2XQy
    t9Ap3S8uelqomkFcF2X+DXuzttrJ5Qe3ze4p49EysS6OWzK3uSPozkJddMY72dvt
    i0a09TnXGbxKDLSdiFl448yNIzhW+tWMkR6eg7OSOTSiiPMRN8NWPlS25P7yaw9N
    yHlkwW3lL+H8ZPUmePebjMtFLiycy6TGPDN8AekTi0HJSXVy7ZLENQtjTl1jdvAi
    sO9eEFP9GzsHQJCHTVFPRW/CyPCXxqcnF6Bg2wULToBe7BnGtles+lI0W323lwVP
    6cvZBvfvjhF38OExeAi5XkE2xaImvlgYYmPIjK0ac/AtiD7nCe+k6aTU2SaEsQnY
    4bECAwEAAaMXMBUwEwYDVR0lBAwwCgYIKwYBBQUHAwIwDQYJKoZIhvcNAQELBQAD
    ggEBAKJLLuS7IXKkiIkYRRX4wtEA5nOxmAoTCJhkLdmyu6YrU1vBdv8nnf+zG/vd
    tn2ONCzB0XKFXIcwAU7M8XgMcVBbDAPAbRvq9+P+j6qGHuSNc1WxHXd7nFBFVPm+
    mTqbC5JaACMEv93d37GDarPBd7FSOZ7mgq4wWzni+floxbq0w5nhipSobIqZefnf
    QoCglBXU+5CllacINgymR8bNY0SmTrf8Kuw3ZZeo4Z6BxZHLuS+jbl/3qr2NgPbl
    JHrigkOl+DoMwCjwj//+aUk/c4iv53RvnwgC1pwgwF+avGLLL4Xj9//vXj7R4GYB
    DQ/VTShCh9zsDNxCu6DZbhiKKDI=
    -----END CERTIFICATE-----
  client.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAvqzF9B1XrXQZIQHZdDK30CndLy56WqiaQVwXZf4Ne7O22snl
    B7fN7inj0TKxLo5bMre5I+jOQl10xjvZ2+2LRrT1OdcZvEoMtJ2IWXjjzI0jOFb6
    1YyRHp6Ds5I5NKKI8xE3w1Y+VLbk/vJrD03IeWTBbeUv4fxk9SZ495uMy0UuLJzL
    pMY8M3wB6ROLQclJdXLtksQ1C2NOXWN28CKw714QU/0bOwdAkIdNUU9Fb8LI8JfG
    pycXoGDbBQtOgF7sGca2V6z6UjRbfbeXBU/py9kG9++OEXfw4TF4CLleQTbFoia+
    WBhiY8iMrRpz8C2IPucJ76TppNTZJoSxCdjhsQIDAQABAoIBAQCaf8Z6chgsLOl7
    rFL1626zlmhppaBwuzMaiLNQ6lUkic89YuBYq5+KPpkhVpDo52KQKvwyU55lefJ3
    +eEiak0zQsd9UYTB48J9yzPDQ8hZY3dJXHks9hRUmh6fL3l448ZSJf5oIgapf/T3
    e5gyM1Wgv3pYQJ/W3jszxTO5dmnT/dY/BEYlEQPLj0wX+jmJd0perFmMPfLPdfJr
    4Ji2Tilbj+gGmm/v8MGSol8h5sMcCBGKjGdn/H3aoYsnn3DA+31oAnKFclyduHh1
    Orpq36lK7iwpIJ3Jyngd6/q+2I0/jAh4gILpD7uf87uRg9oxQD7yB2Fqpn/j8FXx
    y5nICFydAoGBAPu5OLghDmfD7cbqwLJDIsAfSSzwLQgtITALGulS9+D41MPXJ4c9
    vzLRWJq+NvBahlYH7HBrFks1nuGmLrrSLoWmcoHpXipIyXV1VqzPwS8DvCpzS3CC
    8I1jdnSaMqI5bulQGk2XwOEeGb/hxreu+xohzC4gLtVeZUmP6I+RRg7HAoGBAMHq
    CxLPHWyo916PZSAuMb0KQEFH2cUS78Fbig96R5H2u5KAtT8/R6ud/Iw1jWfqAI1f
    R+/EJy1x8FZDGvTbQfrXsvhNIui8/11Pl0CF6RwLL/h/KS9ZMyA/mqmYuyzHfSg4
    w3OEBoMK/0unJk4s8osukbV/yvOy4Qiujp1+QHPHAoGBAM0GgNcgPX5wzAN/gzHu
    kqhPEyfh+5u0PlrGQMYYCMOZiJp2bMCvn0KB1pw7H75GzTHXRFIQNtlNNDpwQ5Fw
    zemXt55ueH8SR9w+lTkuAhgL/7/HpoNecxWGFJ5GVcVh6B9qWfInDzeMb8ak21kS
    0XzoWEidd+fb+b2f0/jTh29TAoGAGVMmlRNFhX5fqBLUIyrFRioDkEMA9tLtSvRY
    iILwu+hcQNrcUOFDy+77H5iS2iJeZhguferBLxc1Sx7Cc337FPZ8oh740ypzs00E
    tOGIOyhe4HZC+7MLkUedPE79CvEWsF0RcZGphA24n7m5r/YAyxqO3wRMjh0rdIXP
    jFQDuNsCgYB7lb97s9nGS2AqdYjcKyqsQd9gfke8zwlmandAy/56HUP/7Z4ZPue6
    hcb50pgo+vg5zTTJqN1Rv5otnu9nMMXqu//znTjjakq8Sqfn3SoVZ2tfX30CGkpu
    ZqPkpJhNC88OKtvwCEJwqSdVSkEFMyvwnF8RYj+lZaU71utEfy4IAw==
    -----END RSA PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: https-signage
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDDjCCAfagAwIBAgIUQRSYSLXNySewwTfcHnO4TBsuzPowDQYJKoZIhvcNAQEL
    BQAwIDEeMBwGA1UEAwwVU21hcnRQYXJraW5nIExvY2FsIENBMB4XDTI1MDgyMjIy
    Mjk0NloXDTI4MDgyMjIyMjk0NlowHjEcMBoGA1UEAwwTc21hcnQtcGFya2luZy5s
    b2NhbDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALdzs5fLbZe2nVi8
    nRZiBvT86wFDN2FAnGtOo2Yo827Kn0xQineF9+xaDqKTG4liV88qFw6QAk88w5Jm
    39Q+WGyGb2iu+QrVjjHd/rNhVRPoBMHlpri24WA54+bbgjFAAfyG5OlOuEzkCekj
    UBIoVM4fKfSHKrg8oCnP2xrTekc2H4RsYbQe3oriQHja00GvDb1q0afIotMyUqF3
    PPiyFtEzy7eeVFu5RKvMQSQeWzyrs9rORP02wY2R+1bwyzFuMnSYbFanK0r9Ehrf
    r3ZIjX5RgL3+Wh+qRvIPP8hy+SFcMLM93SyBcu+69LACogKYWPBr0lJ6Hm8IQ8g5
    TRTBj1cCAwEAAaNCMEAwKQYDVR0RBCIwIIIHc2lnbmFnZYIKbW9iaWxlLWFwaYIJ
    bG9jYWxob3N0MBMGA1UdJQQMMAoGCCsGAQUFBwMBMA0GCSqGSIb3DQEBCwUAA4IB
    AQBdoahperI/qB92WU0rrKr/zDWJvlgpNCo1+bDkzC7Vn27n7uQNB9zd1A6bhJS3
    9rBJyjKRj4gmK071TE5ZBvMWgJF4QtWLH9cDt54+nqHdxmQUG3Jd0w2W6vMiqVpV
    XGnLG1zSw1AJlXOBkpxczHB5nue8li0qaex5Moo3XX1AzplCCWXFnu+lUHuRRAY7
    Eku8TASoujlhS+ZdEXk7zs0TafzLXF8/9zCwhtnRaQTpgQDabAmFQ/g3pSqeXtOs
    wAWanRkDKmuobxHzf0rcQLPi37OpPewIaguH6PaBENuzMc9Ha33A+/JXDTtDpGyj
    Z2jxs5719k1KBmqnJ5nfanAg
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAt3Ozl8ttl7adWLydFmIG9PzrAUM3YUCca06jZijzbsqfTFCK
    d4X37FoOopMbiWJXzyoXDpACTzzDkmbf1D5YbIZvaK75CtWOMd3+s2FVE+gEweWm
    uLbhYDnj5tuCMUAB/Ibk6U64TOQJ6SNQEihUzh8p9IcquDygKc/bGtN6RzYfhGxh
    tB7eiuJAeNrTQa8NvWrRp8ii0zJSoXc8+LIW0TPLt55UW7lEq8xBJB5bPKuz2s5E
    /TbBjZH7VvDLMW4ydJhsVqcrSv0SGt+vdkiNflGAvf5aH6pG8g8/yHL5IVwwsz3d
    LIFy77r0sAKiAphY8GvSUnoebwhDyDlNFMGPVwIDAQABAoIBAE6MduBO1Rz5rwOY
    tvYngO0TAhinTCYTASadJC+Q5zKQBYcqkS8+KHqF0PBhZo/7kLd+QSMWHDcLQH4G
    GF6LV1cYdMlw6eduqxTFBdKOoVwFo0vWZf1/KJ8ICoIFiQhHbNJQe+E9uIILvgaZ
    /SXZKP6cr10pJux94OImQp2I4TltxIkbW8iGV6Vwp9l4NLeLtHPAPrRqPaT5oaKB
    RSRqe23SlBWrKuKMgV1LC4GmTKDKCNSaRJALLPbNbxO0OJPaCfXqsXKvA2Nzxnld
    mztvGv5VkGnwN1n5zQDVVPLNqPOnUXwDRjjQqKQItSS0ecd7dvfINGY7eJ4n5ha/
    LO0lY+ECgYEA3paED5XCfFP9SoM4MWhG9KBgqrPfdS34/kh1uCVaToO0Wailntv9
    CDL8gesCB1cG+NbpB19j+v+i6bo8JtWr3cFVDMeyOn6x0ngmpgDsDakyaOz4Pzqa
    DLv2UOh2eKfyl+u1axrxznYPrtnT3fRC6fGxf3aa3D4vQEHOlN4rvpECgYEA0v1K
    MXDujO4ixoTUQBueDSrTxmhIu1wedOyy4chRD2nhHfXojBChzsdt/KaiQnr/t630
    weNFFiS+A//XpPNlS+D0SGaesPgqNK/QRInbisasuHMK0amwi7XTQPZZr6x4qqz6
    arbz5l+VT+ntpD6Z6BUF15Eg8gV9lxMEkpGhM2cCgYEAvIrweCcZ46hdQDWgbrFu
    kR4cY9wTJzX22KXWGVKCiUkkhmHFUKf1UHGn1ACV6lO8UyHvp9AUZ3MMs0COXTLW
    7vMpsLai8MuKosYlrq3PRc8RJTG9IgnonWrFvUj7uT5Bzo/ZT002j/UPWcOnpDWY
    TIPvHxH/IRoHej2D2DPNCBECgYEAxhiCfIEnuLItfG5iSf6kGoDHbVWkVCVdgzJp
    kYtecDZc4qBrwnYrNdYQ8lIRrpGFXpO5ZgFYcD33GhIwCfNsfB2tvfx7qnSWS/l2
    daNpuZZnvJZm5guIcuQ4gJnMAyDP+o+GXoN/5CCCNBHSyY7tOfXjEk50vEdjb2Cv
    vl11GKkCgYBBCB0YrkLIIj5Y8XZBzAQzCuhbIKuKKl92Zy2jIYaGsPMa+wgMAN2R
    m31XBM5emrtujSVCWupebpFyw2ErABMaXR3ESb9geETf2fvpDnfeqQLtEtSTrJqM
    Wq3w5iLt4K7cNVgK5wnGibx3FwMaq0DCCFs+iqM9bC+RtSUyM7iGpQ==
    -----END RSA PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: https-mobile-api
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDDjCCAfagAwIBAgIUQRSYSLXNySewwTfcHnO4TBsuzPowDQYJKoZIhvcNAQEL
    BQAwIDEeMBwGA1UEAwwVU21hcnRQYXJraW5nIExvY2FsIENBMB4XDTI1MDgyMjIy
    Mjk0NloXDTI4MDgyMjIyMjk0NlowHjEcMBoGA1UEAwwTc21hcnQtcGFya2luZy5s
    b2NhbDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALdzs5fLbZe2nVi8
    nRZiBvT86wFDN2FAnGtOo2Yo827Kn0xQineF9+xaDqKTG4liV88qFw6QAk88w5Jm
    39Q+WGyGb2iu+QrVjjHd/rNhVRPoBMHlpri24WA54+bbgjFAAfyG5OlOuEzkCekj
    UBIoVM4fKfSHKrg8oCnP2xrTekc2H4RsYbQe3oriQHja00GvDb1q0afIotMyUqF3
    PPiyFtEzy7eeVFu5RKvMQSQeWzyrs9rORP02wY2R+1bwyzFuMnSYbFanK0r9Ehrf
    r3ZIjX5RgL3+Wh+qRvIPP8hy+SFcMLM93SyBcu+69LACogKYWPBr0lJ6Hm8IQ8g5
    TRTBj1cCAwEAAaNCMEAwKQYDVR0RBCIwIIIHc2lnbmFnZYIKbW9iaWxlLWFwaYIJ
    bG9jYWxob3N0MBMGA1UdJQQMMAoGCCsGAQUFBwMBMA0GCSqGSIb3DQEBCwUAA4IB
    AQBdoahperI/qB92WU0rrKr/zDWJvlgpNCo1+bDkzC7Vn27n7uQNB9zd1A6bhJS3
    9rBJyjKRj4gmK071TE5ZBvMWgJF4QtWLH9cDt54+nqHdxmQUG3Jd0w2W6vMiqVpV
    XGnLG1zSw1AJlXOBkpxczHB5nue8li0qaex5Moo3XX1AzplCCWXFnu+lUHuRRAY7
    Eku8TASoujlhS+ZdEXk7zs0TafzLXF8/9zCwhtnRaQTpgQDabAmFQ/g3pSqeXtOs
    wAWanRkDKmuobxHzf0rcQLPi37OpPewIaguH6PaBENuzMc9Ha33A+/JXDTtDpGyj
    Z2jxs5719k1KBmqnJ5nfanAg
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAt3Ozl8ttl7adWLydFmIG9PzrAUM3YUCca06jZijzbsqfTFCK
    d4X37FoOopMbiWJXzyoXDpACTzzDkmbf1D5YbIZvaK75CtWOMd3+s2FVE+gEweWm
    uLbhYDnj5tuCMUAB/Ibk6U64TOQJ6SNQEihUzh8p9IcquDygKc/bGtN6RzYfhGxh
    tB7eiuJAeNrTQa8NvWrRp8ii0zJSoXc8+LIW0TPLt55UW7lEq8xBJB5bPKuz2s5E
    /TbBjZH7VvDLMW4ydJhsVqcrSv0SGt+vdkiNflGAvf5aH6pG8g8/yHL5IVwwsz3d
    LIFy77r0sAKiAphY8GvSUnoebwhDyDlNFMGPVwIDAQABAoIBAE6MduBO1Rz5rwOY
    tvYngO0TAhinTCYTASadJC+Q5zKQBYcqkS8+KHqF0PBhZo/7kLd+QSMWHDcLQH4G
    GF6LV1cYdMlw6eduqxTFBdKOoVwFo0vWZf1/KJ8ICoIFiQhHbNJQe+E9uIILvgaZ
    /SXZKP6cr10pJux94OImQp2I4TltxIkbW8iGV6Vwp9l4NLeLtHPAPrRqPaT5oaKB
    RSRqe23SlBWrKuKMgV1LC4GmTKDKCNSaRJALLPbNbxO0OJPaCfXqsXKvA2Nzxnld
    mztvGv5VkGnwN1n5zQDVVPLNqPOnUXwDRjjQqKQItSS0ecd7dvfINGY7eJ4n5ha/
    LO0lY+ECgYEA3paED5XCfFP9SoM4MWhG9KBgqrPfdS34/kh1uCVaToO0Wailntv9
    CDL8gesCB1cG+NbpB19j+v+i6bo8JtWr3cFVDMeyOn6x0ngmpgDsDakyaOz4Pzqa
    DLv2UOh2eKfyl+u1axrxznYPrtnT3fRC6fGxf3aa3D4vQEHOlN4rvpECgYEA0v1K
    MXDujO4ixoTUQBueDSrTxmhIu1wedOyy4chRD2nhHfXojBChzsdt/KaiQnr/t630
    weNFFiS+A//XpPNlS+D0SGaesPgqNK/QRInbisasuHMK0amwi7XTQPZZr6x4qqz6
    arbz5l+VT+ntpD6Z6BUF15Eg8gV9lxMEkpGhM2cCgYEAvIrweCcZ46hdQDWgbrFu
    kR4cY9wTJzX22KXWGVKCiUkkhmHFUKf1UHGn1ACV6lO8UyHvp9AUZ3MMs0COXTLW
    7vMpsLai8MuKosYlrq3PRc8RJTG9IgnonWrFvUj7uT5Bzo/ZT002j/UPWcOnpDWY
    TIPvHxH/IRoHej2D2DPNCBECgYEAxhiCfIEnuLItfG5iSf6kGoDHbVWkVCVdgzJp
    kYtecDZc4qBrwnYrNdYQ8lIRrpGFXpO5ZgFYcD33GhIwCfNsfB2tvfx7qnSWS/l2
    daNpuZZnvJZm5guIcuQ4gJnMAyDP+o+GXoN/5CCCNBHSyY7tOfXjEk50vEdjb2Cv
    vl11GKkCgYBBCB0YrkLIIj5Y8XZBzAQzCuhbIKuKKl92Zy2jIYaGsPMa+wgMAN2R
    m31XBM5emrtujSVCWupebpFyw2ErABMaXR3ESb9geETf2fvpDnfeqQLtEtSTrJqM
    Wq3w5iLt4K7cNVgK5wnGibx3FwMaq0DCCFs+iqM9bC+RtSUyM7iGpQ==
    -----END RSA PRIVATE KEY-----